steps:
  # 1. Instala dependências do backend
  - name: "gcr.io/cloud-builders/npm"
    dir: "backend"
    args: ["install"]

  # 2. Deploy do backend (que já tem o frontend/build commitado)
  - name: "gcr.io/k8s-skaffold/pack"
    args:
      - "build"
      - "--builder=gcr.io/buildpacks/builder"
      - "--path=."
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ios_car_api/ios-car-api:$COMMIT_SHA"
    dir: "backend"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ios_car_api/ios-car-api:$COMMIT_SHA"
